### ISSUE TITLE
Update Readme file 

### ISSUE THREAD

**Issue by ksdkamesh99** [garimasingh128/CP-DSA-Cpp-C#1]
Need to update readme file for listing the algorithms present which will give an idea to other contributors to contribute

**Comment by gioboa** [comment]
Can I take this? I will create the list in the readme

**Comment by harshd-eep** [comment]
I would like to work on it.

**Comment by Komal7209** [comment]
Hi, Could I also contribute to this repo... I'm already on 100 days of code in cpp so contributing to this repo would work for me 😁

**Comment by nilam23** [comment]
Can I implement few data structure problems here?

**Comment by amishaagarwal1998** [comment]
> Need to update readme file for listing the algorithms present which will give an idea to other contributors to contribute

I have added topics to the read me file. Please review!

**Comment by crazyvibes** [comment]
I would like to work on it.

**Comment by Kundanvairagade** [comment]
I would like to work on it.

**Comment by AMorr1** [comment]
i would like to contribute as i have contributed a lot before in dsa.

**Comment by sakshi0461** [comment]
I would like to contribute in it

**Comment by Harshsngh07** [comment]
Would like to work on the issue.

**Comment by tanujajoshi1** [comment]
I would like to make a contribution to it

**Comment by EthicalRohit** [comment]
I would like to work with u

**Comment by rodrigueseva** [comment]
I would like to work for it, Please assign it to me :)

**Comment by iamskm23** [comment]
I have added topics to the read me file. Please review!
