### ISSUE TITLE
Exclude .exe files from Tracking history for better code organization

### ISSUE THREAD

**Issue by psk907** [garimasingh128/CP-DSA-Cpp-C#22]
### Tasks
- Delete existing .exe files from the repository
- Add a .gitignore file to exclude subsequent .exe files from being tracked by version control.

### Purpose
Executable files are created by the system upon compilation and are required only for running the code. Hence it is not required to be tracked by version control.

### Result
This would result in a cleaner and more professional repository.

**Comment by psk907** [comment]
@garimasingh128 I'd love to work on this myself, please assign me to it.

**Comment by sahuaman83** [comment]
@garimasingh128 I would love to work on this please assign it to me.

**Comment by hiruthicShaSS** [comment]
Cleaned the executables and added those file extensions in .gitignore file. Pull Request: #58
